## 4.2.4
**`(fix):`** Datetime examples are generated correctly once again.
The `pydantic_utilities` file is python 3.8 compatible.


